events {
    worker_connections  1024;
}

http {
    server {
        # Listen endpoint
        listen 443 ssl;
        server_name obednaou.42.fr;

        # TLS configuration
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_certificate /etc/nginx/ssl-config/self-signed.crt;
        ssl_certificate_key /etc/nginx/ssl-config/private.key;

        # Root and indices
        root /var/www/wordpress;
        index index.php;

        # WordPress
        location / {
            try_files $uri $uri/ =404;
        }

        location ~ \.php$ {
            fastcgi_pass wordpress:9000;
            include snippets/fastcgi-php.conf;
        }

        # PHPMyAdmin
        location /phpmyadmin {
            alias /var/www/phpmyadmin;
            index index.php;
            try_files $uri $uri/ =404;
        }

        location ~ ^/phpmyadmin/(.+\.php)$ {
            alias /var/www/phpmyadmin/$1;
            fastcgi_pass phpmyadmin:9000;
            include snippets/fastcgi-php.conf;
        }
    }
}
